name: Docker build PR check

on:
  pull_request:

jobs:
  docker-build-pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --platform linux/amd64 -t auth-mini:pr-check .
